[[part-three-spring-data-aerospike]]
= Spring Boot Web Application using Spring Data Aerospike

In the first part of this tutorial series on creating a web application using Spring Boot, I showed how to create the Maven project with Spring Boot. 

In the second part, I showed you how to configure Spring MVC and ThymeLeaf templates to display a basic web page via Tomcat. 

In this part we’ll connect to an Aerospike server via Spring Data Aerospike. We will use these tools to persist data to Aerospike in our Spring Boot Web Application.

== Aerospike Persistence with Spring Boot

Spring Boot comes with pre-configured options for relational databases. Like other things in Spring Boot, these are enabled by simply having the dependency on your classpath.

However this tutorial will focus around Aerospike No-SQL database.  Spring Data does a great job of abstracting the persistence layer.  We will incorporate Spring Data Aerospike, create some entities and persist them using Spring Data Repository.

== Aerospike

Aerospike is the company behind the Aerospike open source NoSQL distributed database which has a horizontally scalable high-speed lightweight data layer.  Open source, flash optimized, in-memory database & key-value store+ for mission critical apps requiring blazing speed, cost efficient scaling & no downtime.

Aerospike is developed and optimized for 64-bit Linux. Aerospike supports popular Linux distributions, with .rpm packages for Red Hat variants, .deb packages for Ubuntu and Debian, binary packages and source builds.

Aerospike provides an https://aws.amazon.com/amazon-linux-ami/[Amazon Linux AMI], prebuilt with the required dependencies. Other cloud providers are supported as well.

OS X and Windows are supported using Vagrant managed virtual machines. With the https://vagrantcloud.com/aerospike/[Vagrant cloud] virtual machine distribution system you will be able to download and run Aerospike with a few simple commands.

Configuring Aerospike Server is out of scope please follow the instructions available here http://www.aerospike.com/docs/operations/install/[Install Aerospike]

== Aerospike and Spring Boot

Aerospike is by far the most popular. When you include the Spring Data Aerospike dependency in your Maven POM, Aerospike Spring Data is included by default. As typical with Spring Boot, Spring Data Aerospike is setup and configured with sensible default properties.

[source]
--
pom.xml
--

[source,xml]
----
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-aerospike</artifactId>
			<version>0.0.1-SNAPSHOT</version>		
		</dependency>
----

== Example Entity

In our example application, we’re going to use a product for a ecommerce website.

By convention, I like to put my entity classes in a package called ‘domain’.

[source]
--
Product.Java
--

[source,java]
----
package aerospike.springboot.domain;

import org.springframework.data.annotation.Id;


public class Product {
	@Id
	private Integer id;
	private String productId;
    private String description;
    private String imageUrl;
    private double price;
    
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getProductId() {
		return productId;
	}
	public void setProductId(String productId) {
		this.productId = productId;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getImageUrl() {
		return imageUrl;
	}
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}	
}
----
= Spring Data Aerospike

Using Spring Data Aerospike can save you a lot of time when interacting with the Aerospike. Spring Data Aerospike implements the Repository Pattern. This design pattern was originally defined by Eric Evans and Martin Fowler, in their book Domain Driven Design. This is one of those time test computer science books, over a decade old, still remains relevant today.

You don’t need to use Spring Data Aerospike for this type of project. But using Spring Data Aerospike will make your life as a developer easier. A common alternative to Spring Data Aerospike would be to use the widely accepted DAO pattern, The DAO pattern is very similar to the Repository Pattern. The advantage of using Spring Data Aerospike is that you’ll be writing a lot less code. Spring Data Aerospike works a lot like Spring Integration Gateways, where you define an interface, and Spring provides the implementation at run time.

== Spring Data Aerospike CRUD Repository

The Spring Data Aerospike CRUD Repository is my favorite feature of Spring Data Aerospike. Similar to coding with a Spring Integration Gateway, you can just define an interface. Spring Data Aerospike uses generics and reflection to generate the concrete implementation of the interface we define.

Defining a repository for our Product domain class is as simple as defining a interface and extending the CrudRepository interface. You need to declare two classes in the generics for this interface. They are used for the domain class the repository is supporting, and the type of the id declared of the domain class.

For our Product domain class we can define a Spring Data Aerospike repository as follows.

[source]
--
ProductRepository.java
--

[source,java]
----
package aerospike.springboot.repositories;

import org.springframework.data.aerospike.core.AerospikeOperations;
import org.springframework.data.aerospike.repository.AerospikeRepository;

import aerospike.springboot.domain.Product;

public interface ProductRepository extends AerospikeRepository<Product, Integer> {
}
----

== Integration Testing with Spring Data Aerospike and JUnit

For our integration tests, we’re going to use a Spring Context to wire up beans to support our tests. If we were not using Spring Boot, we’d need to create a number of beans ourselves. Normally we would need to create:

* Aerospike Client
* Aerospike Template 
* A Transaction Manager

But since we’re using Spring Boot, we don’t need to write code to create these beans. For the purposes of our integration tests for our Spring Data Aerospike repositories, we can complete our Java configuration with just annotations.

[source]
--
RepositoryConfiguration.java
--

[source,java]
----
package aerospike.springboot.configuration;

import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.aerospike.core.AerospikeTemplate;
import org.springframework.data.aerospike.repository.config.EnableAerospikeRepositories;
import org.springframework.transaction.annotation.EnableTransactionManagement;

import com.aerospike.client.AerospikeClient;
import com.aerospike.client.policy.ClientPolicy;

@Configuration //<1>
@EnableAerospikeRepositories(basePackages = {"aerospike.springboot.repositories"}) //<2>
@EnableAutoConfiguration
@EnableTransactionManagement //<3>
public class RepositoryConfiguration {
	
	public @Bean(destroyMethod = "close") AerospikeClient aerospikeClient() { //<4>

		ClientPolicy policy = new ClientPolicy();
		policy.failIfNotConnected = true;

		return new AerospikeClient(policy, "localhost", 3000); //<5>
	}

	public @Bean AerospikeTemplate aerospikeTemplate() { //<6>
		return new AerospikeTemplate(aerospikeClient(), "test");
	}

}
----
<1> *@Configuration*  tells the Spring Framework this is a Java configuration class.
<2> *@EnableAerospikeRepositories(basePackages = {"aerospike.springboot.repositories"})"*  tells Spring Boot to do its auto configuration magic. This is what has Spring Boot automatically create the Spring Beans with sensible defaults for our tests.
<3> *@EnableTransactionManagement* Enables Spring’s annotation driven transaction management
<4> *@Bean* Configuration for AerospikeClient 
<5>  Host and port of Aerospike server
<6>  *@Bean* Configuration for AerospikeTemplate 

Through this configuration, we have everything we need to use Aerospike with Spring Data Aerospike in JUnit tests.

== Spring Data Aerospike JUnit Integration Test

With our Spring Java configuration done, our JUnit integration test becomes very simple to write. 

In this post, I am not going to go in depth with Spring Data Aerospike. This is fairly large and complex project in the Spring Framework. We’re going to use the CRUD repository from Spring Data Aerospike. CRUD stands for CReate, Update, Delete. Your basic persistence operations. Simply extending the Spring Data Aerospike’s CRUD Repository interface, as we did above, for the specified Entity we will get methods which will:

* Save an entity
* Find an entity based on its ID
* Check if an entity exists based on its ID
* Get a list of all entities
* Get a count of all entities
* Delete an entity
* Delete all entities

I’ve written a simple integration test for the Spring Data Aerospike repository I defined above. In the test, I’m going to do some basic operations, like creating an entity, saving an entity, and fetching an entity from Aerospike. While I’ve written a minimal amount of code in this example, the data is really getting saved into Aerospike. You don’t see any aerospike code happening, but it is getting generated behind the scenes for us.  Once you grasp how little code you are writing, and how much is happening under the covers for you, you can appreciate what a powerful tool Spring Data Aerospike is.

[source]
--
ProductRepositoryTest.java
--

[source,java]
----
package aerospike.springboot.repositories;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import aerospike.springboot.configuration.RepositoryConfiguration;
import aerospike.springboot.domain.Product;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = {RepositoryConfiguration.class})
public class ProductRepositoryTest {
	
	private ProductRepository productRepository;
	
	@Autowired
    public void setProductRepository(ProductRepository productRepository) {
        this.productRepository = productRepository;
    }
	
	@Test
	public void testSaveProduct(){
		Product product = new Product();
        product.setDescription("Spring Data Aerospike Shirt");
        product.setPrice(18.95);
        product.setProductId("1234");
        product.setId(100);

        productRepository.save(product);
        assertNotNull(product.getId()); //not null after save
        
      //fetch from DB
        Product fetchedProduct = productRepository.findOne(product.getId());

        //should not be null
        assertNotNull(fetchedProduct);
        
        //should equal
        assertEquals(product.getId(), fetchedProduct.getId());
        assertEquals(product.getDescription(), fetchedProduct.getDescription());

        //update description and save
        fetchedProduct.setDescription("New Description");
        productRepository.save(fetchedProduct);

        //get from Aerospike, should be updated
        Product fetchedUpdatedProduct = productRepository.findOne(fetchedProduct.getId());
        assertEquals(fetchedProduct.getDescription(), fetchedUpdatedProduct.getDescription());

        //verify count of products in DB
        long productCount = productRepository.count();
        assertEquals(productCount, 1);

        //get all products, list should only have one
        Iterable<Product> products = productRepository.findAll();

        int count = 0;

        for(Product p : products){
            count++;
        }

        assertEquals(count, 1);

	}
}
----

== Loading Data Using Spring Data on Startup
=== Creating a Product Loader

The Spring Framework comes out the of box with a number of events, and you’re able to extend the event functionality for your own purposes.

Under the scenario we want to do something on startup we have two events we can consider using. Traditionally under Spring Framework, we can use the ContextRefreshedEvent. This event has been around since the beginning of the Spring Framework.

If you’re using Spring Boot, you do have additional events to select from. I often want to use a startup event to seed data for tests, so in this case, I need the database connection to be setup. Reading about the Spring Boot Events, I thought the event I would like to use is ApplicationPreparedEvent. But in testing it out, this was not the case. I ran into some issues with getting the event listeners setup properly in the Spring Boot Context. I found better results using the ContextRefreshedEvent.

[source]
--
ProductLoader.java
--


This class implements the ApplicationListner interface, so it is called with the ContextRefresedEvent on startup. We’re using Spring to inject the Spring Data Aerospike repository into the class for our use. In this example, I’m creating two entities and saving them into Aerospike.

[source,java]
----
package aerospike.springboot.bootstrap;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationListener;
import org.springframework.context.event.ContextRefreshedEvent;
import org.springframework.stereotype.Component;

import aerospike.springboot.domain.Product;
import aerospike.springboot.repositories.ProductRepository;

@Component
public class ProductLoader
		implements ApplicationListener<ContextRefreshedEvent> {

	private ProductRepository productRepository;

	private Logger log = Logger.getLogger(ProductLoader.class);

	@Autowired
	public void setProductRepository(ProductRepository productRepository) {
		this.productRepository = productRepository;
	}

	@Override
	public void onApplicationEvent(ContextRefreshedEvent event) {
		productRepository.deleteAll();
		Product shirt = new Product();
		shirt.setId(10001);
		shirt.setDescription("Aerospike Shirt");
		shirt.setPrice(18.95);
		shirt.setImageUrl(
				"http://hunt4freebies.com/wp-content/uploads/2014/07/Aerospike-T-shirt.png");
		shirt.setProductId("235268845711068308");
		productRepository.save(shirt);

		log.info("Saved Shirt - id: " + shirt.getId());

		Product mug = new Product();
		mug.setId(10002);
		mug.setDescription("Aerospike Mug");
		mug.setPrice(4.99);
		mug.setImageUrl(
				"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR3TPM0daB-aXKfxdYqlHHgQrz67bSCPKUcpbmzPXtvo3GillfR");
		mug.setProductId("168639393495335947");
		productRepository.save(mug);

		log.info("Saved Mug - id:" + mug.getId());
	}

}

----

=== Running Product Loader

We still have our Spring Boot application class which was created earlier.

[source]
--
SpringBootWebApplication.java
--

[source,java]
----
package aerospike.springboot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringBootWebApplication {
 
    public static void main(String[] args) {
        SpringApplication.run(SpringBootWebApplication.class, args);
    }
}

----
When we run this class, it will startup tomcat for us. In the console log, we can see the output of the log statements from our ProductLoader  class.
[source,java]
----
Deleted 2 records from set Product
2015-09-16 15:37:17.121  INFO 110684 --- [           main] a.springboot.bootstrap.ProductLoader     : Saved Shirt - id: 10001
2015-09-16 15:37:17.121  INFO 110684 --- [           main] a.springboot.bootstrap.ProductLoader     : Saved Mug - id:10002
2015-09-16 15:37:17.183  INFO 110684 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2015-09-16 15:37:17.199  INFO 110684 --- [           main] a.springboot.SpringBootWebApplication    : Started SpringBootWebApplication in 6.402 seconds (JVM running for 11.639)
----

To run the Spring Boot application, simply right click on the SpringBootWebApplication class and select “Run ‘SpringBootWebApplica…'”

== Conclusion

In this part of my tutorial series on creating a web application using Spring Boot, I’ve shown you how to setupAerospike and Spring Data Aerospike for use. You can see how easy it is to persist data to Aerospike using Spring Data JPA repositories.

